### ISSUE TITLE
Update state config to be nested

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#137]
Right now the state config requires us to put the `state` key at the top of the toml file since if it's not then it will get nested inside another section. For example if we have the config:

```toml
[graph]
edge_list_input_file = "../data/tomtom_denver/edges-compass.csv.gz"
vertex_list_input_file = "../data/tomtom_denver/vertices-compass.csv.gz"
verbose = true

state = [
    { distance_unit = "kilometers", initial = 0.0 },
    { time_unit = "minutes", initial = 0.0 },
]
```

state would get nested under the `graph` key. 

We could update this to have a nested entry so it could be placed anywhere in the toml file, something like:

```toml
[state_model]
state = [
    { distance_unit = "kilometers", initial = 0.0 },
    { time_unit = "minutes", initial = 0.0 },
]
```
