### ISSUE TITLE
general CSV ResponseOutputPolicy

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#164]
a user should be able to specify a response output policy format targeting a CSV file. 

to make it general, a user should be allowed to specify the relevant fields to flatten onto the CSV row as a key/value mapping from destination keys to their dot-delimited JSON paths. for example:

```toml
[response_output_policy]
type = "run_batch_file_sink"
filename = "mep_denver_output.csv"
[response_output_policy.format]
type = "csv" 
[response_output_policy.format.mapping]
src_edge = "request.origin_edge_id"
dst_edge = "request.destination_edge_id"
cost = "cost.total_cost"
```
