### ISSUE TITLE
Rewrite more robust UUID plugin

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#265]
the current UUID output plugin expects queries that are tagged with {origin|destination}_vertex fields and looks up those values in a lookup table to append UUIDs. it fails if the vertex data is missing from the query.

let's refactor this so that instead, in configuration, we have

```toml
[[output_plugins]]
type = "UUID"
vertex_uuid_input_file = ""  # optional
edge_uuid_input_file = ""  # optional
```

during `UuidOutputPlugin::process`, we check for the following cases for each combination of origin/destination/edge/vertex:

```rust
match (query.get_origin_vertex(), self.vertex_uuids) {
  (Some(vertex_id), Some(vertex_uuids)): (Option<VertexId>, Option<Box<[String]>>) => { append_uuid() },
  _ => {} // do nothing, as opposed to failing here 
}
```
