### ISSUE TITLE
Update traversal model unit representation

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#279]
Our current traversal model unit representation could be a little bit clearer. For example, we might have a config that looks like this:

```toml
[traversal]
type = "energy_model"
time_model_speed_unit = "kilometers_per_hour"
grade_table_input_file = "edges-grade-enumerated.txt.gz"
grade_table_grade_unit = "decimal"

time_unit = "minutes"
distance_unit = "miles"

[traversal.time_model]
type = "speed_table"
speed_table_input_file = "edges-posted-speed-enumerated.txt.gz"

speed_unit = "kilometers_per_hour"
distance_unit = "miles"
time_unit = "minutes"
```

Looking at the traversal.time_model section, it's unclear what the units represent. For example, the `speed_unit` field is used to indicate what units will be found in the `speed_table_input_file` but the `distance_unit` is used as the unit that the time model outputs. We also have the key `time_model_speed_unit` which could be mistakenly set differently from the `speed_unit` key with no error thrown.

Let's think about how to make these more clear for the user even if that's just updating their name so that `speed_unit` might `speed_table_speed_unit` and `time_unit` might become `output_time_unit`. 

We might also be able to get the time model speed units directly from the model rather than making the user set it.
