### ISSUE TITLE
inconsistent use of FromStr / Deserialize of some units

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#309]
The EnergyRateUnit deserializer is customized so that it expects strings of the format "<energy_unit>/<distance_unit>" or "<distance_unit>/<energy_unit>". under-the-hood, it uses FromStr<EnergyUnit> and FromStr<DistanceUnit>. however, EnergyUnit and DistanceUnit use a default Deserialize method. the strings they support are not the same, so:

```toml
# valid EnergyUnit deserializing uses the serde::Deserialize macro with `rename_all = "snake_case"`
energy_unit_01 = "kilowatt_hours"
# valid EnergyRateUnit deserializing uses FromStr<EnergyUnit> instead:
energy_rate_unit_01 = "kilowatthour/miles"
energy_rate_unit_02 = "kilowathours/miles" # <-- also, typo here
energy_rate_unit_03 = "kwh/miles"
```

these should be unified, via leveraging FromStr implementations in a custom deserialize implementation in DistanceUnit + EnergyUnit.
