### ISSUE TITLE
expected query to be a json object '{}' but found Object {"origin_name": String("NREL"),

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#314]
While attempting to run a scenario with a grid search, I received the following error message. It is cryptic, it does not clearly point to the issue, which is that the top-level `value` of a grid search is expected to be a JSON object.

### Offending data

```toml
[[plugin.input_plugins]]
type = "inject"
format = "key_value"
write_mode = "overwrite"
key = "grid_search"
value = [
    { name = "t1", weights = { distance = 0, time = 1, energy_liquid = 0, energy_electric = 0 } },
    { name = "e1", weights = { distance = 0, time = 0, energy_liquid = 1, energy_electric = 1 } },
]
```

### Fix

```toml
[[plugin.input_plugins]]
type = "inject"
format = "key_value"
write_mode = "overwrite"
key = "grid_search"
value.variants = [
    { name = "t1", weights = { distance = 0, time = 1, energy_liquid = 0, energy_electric = 0 } },
    { name = "e1", weights = { distance = 0, time = 0, energy_liquid = 1, energy_electric = 1 } },
]

```

### Error message

```
expected query to be a json object '{}' but found Object {"origin_name": String("NREL"), "destination_name": String("Comrade Brewing Company"), "destination_y": Number(39.62627481432341), "destination_x": Number(-104.9946020751972), "origin_y": Number(39.798311884359094), "origin_x": Number(-104.86796368632216), "starting_soc_percent": Number(100), "model_name": String("2016_TOYOTA_Camry_4cyl_2WD"), "start_time": String("05:00:00"), "start_weekday": String("monday"), "weights": Object {"distance": Number(0), "time": Number(1), "energy_electric": Number(0)}, "vehicle_parameters": Array [Object {"type": String("height"), "value": Number(10), "unit": String("feet")}, Object {"value": Number(6), "type": String("width"), "unit": String("feet")}, Object {"value": Number(40), "type": String("total_length"), "unit": String("feet")}, Object {"unit": String("feet"), "value": Number(30), "type": String("trailer_length")}, Object {"value": Number(60000), "unit": String("pounds"), "type": String("total_weight")}, Object {"type": String("weight_per_axle"), "unit": String("pounds"), "value": Number(12000)}], "road_classes": Array [Number(1), Number(2), Number(3), Number(4), Number(5), Number(6)], "grid_search": Array [Object {"weights": Object {"distance": Number(0), "energy_liquid": Number(0), "time": Number(1), "energy_electric": Number(0)}, "name": String("t1")}, Object {"name": String("e1"), "weights": Object {"distance": Number(0), "energy_liquid": Number(1), "energy_electric": Number(1), "time": Number(0)}}]}
````
