### ISSUE TITLE
missing termination "type" falls back to default even if other fields are present

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#38]
running a configuration with the following:

```toml
[termination]
models = [
    { type = "query_runtime", limit = "00:10:00" },
    { type = "solution_size", limit = 30000000 },
]

```

i would expect this to _fail_, since the (required) `type` field is missing, but instead, it runs. that is because the reified final config, after merging with defaults, looks like this:

```toml
[termination]
type = "query_runtime"
limit = "00:02:00"
frequency = 100_000
models = [
    { type = "query_runtime", limit = "00:10:00" },
    { type = "solution_size", limit = 30000000 },
]
```

here, "models" gets ignored, since the "query_runtime" type is set, and it loads correctly since all fields required are present.

to make it fail, i need to specify an invalid type:

```toml
[termination]
type = "pizza"
models = [
    { type = "query_runtime", limit = "00:10:00" },
    { type = "solution_size", limit = 30000000 },
]
```

which fails as expected:

```
[2023-11-21T20:54:02Z ERROR routee_compass] Could not build CompassApp from config file: unknown module pizza for component termination provided by configuration
Error: CompassConfigurationError(UnknownModelNameForComponent("pizza", "termination"))
```
