### ISSUE TITLE
normalize_file_paths will treat array of strings as array of file paths

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#39]
i have a custom frontier model and it includes an array of strings:

```toml
[frontier]
type = "mep"
time_limit = 40.0
time_index = 2
road_class_input_file = "/Users/rfitzger/dev/nrel/routee/routee-compass-tomtom/data/tomtom_metro_denver_network/edges-road-class-enumerated.txt.gz"
valid_road_classes = ["1", "2", "3", "4", "5", "6"]
```

(this is a wrapper around two other models, one being our built-in road class model)

when i attempt to load this TOML file, i get the following error:

```
Could not find incoming configuration file, tried 1 and configuration/1. Make sure the file exists and that the config key ends with '_input_file'
```

this is because [normalize_file_paths](https://github.com/NREL/routee-compass/blob/main/rust/routee-compass/src/app/compass/config/config_json_extension.rs#L274) assumes all strings are paths and [recurses if it sees an array](https://github.com/NREL/routee-compass/blob/main/rust/routee-compass/src/app/compass/config/config_json_extension.rs#L320).
