### ISSUE TITLE
inject plugin should have overwrite behaviors

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#77]
noting that we have this inject plugin, and some configuration may have it used like this:

```toml
[[plugin.input_plugins]]
type = "inject"
key = "road_classes"
value = '["4","5","6","7"]'
format = "json"
```

what if an incoming query has a "road_classes" key already defined? really, we should be able to control what we do with this by giving inject plugins an "overwrite" behavior. i'm proposing here a taxonomy for overwrite but open to anything along these lines:

```toml
[[plugin.input_plugins]]
type = "inject"
key = "road_classes"
value = '["4","5","6","7"]'
overwrite = ""              # one of "error", "overwrite", "merge", "ignore"
format = "json"
```
where
- "error" - fail on key collision
- "overwrite" - overwrite the user's "road_classes" with those coming from the inject plugin
- "merge" - attempt to merge the values if possible (may still fail)
- "ignore" - pass the user's "road_classes" (a noop for the plugin)
