### ISSUE TITLE
Edge RTree resulting in no path found

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-compass#78]
When using the edge based rtree, with the following config:

<details>

<summary>Config</summary>

```toml
parallelism = 2
search_orientation = "edge"

[graph]
edge_list_input_file = "data/tomtom_metro_denver_network/edges-compass.csv.gz"
vertex_list_input_file = "data/tomtom_metro_denver_network/vertices-compass.csv.gz"
verbose = true

[traversal]
type = "distance"
distance_unit = "miles"

[plugin]
input_plugins = [
    { type = "edge_rtree", geometry_input_file = "data/tomtom_metro_denver_network/edges-geometries-enumerated.txt.gz", road_class_input_file = "data/tomtom_metro_denver_network/edges-road-class-enumerated.txt.gz" },
    { type = "grid_search" },
    { type = "load_balancer", weight_heuristic = { type = "haversine" } },
]
output_plugins = [
    { type = "summary" },
    { type = "traversal", geometry_input_file = "data/tomtom_metro_denver_network/edges-geometries-enumerated.txt.gz" },
]
```

</details>

I get the error:

```console
ERROR routee_compass] Error: "no path exists between vertices 57208 and 356583"
```

There are no restrictions being applied here and so it's not a problem with certain edges being excluded from the search. I wonder if the edge based RTree is starting the search at a terminal vertex?
