### ISSUE TITLE
CostFunction: abstraction or convention

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/routee-compass#83]
aggregating ~arbitrary~ raw state transition data into a cost function is a naive way to estimate the cost of graph traversal and doesn't correctly capture the tradeoffs. we see this in our results, where a simple cost function such as

$$\alpha * t + (1-\alpha) * e$$

where $t$ is the time to traverse a link, $e$ is the energy to traverse a link, and $\alpha$ is a energy/time cost coefficient in the range $[0,1]$.

but since the magnitudes of $T$ and $E$ are different, and $E$ space may not increase monotonically, the composition of these values lacks the invariants of a ~good~ valid cost function for a graph search.

### what we want

we want to combine state transitions in a way that is properly normalized. in this task, we are talking about the software engineering task of designing _how_ we model the function from state transition to `Cost` in code. this could be an abstraction or maybe just a convention, because
1. while an abstraction feels right, it may not be helpful since any `CostFunction` is tightly coupled with it's `TraversalModel` that defines what the state transition variables are
2. but the right abstraction would let us define in one place some aggregation logic that could be applied to arbitrary `TraversalModel`s

### some ideas

here's an idea that doesn't try to solve 100% of the problem but come up with something reasonable to configure. we could provide cost mappings by unit type in configuration of the traversal model. for each unit type in compass, we could have an optional cost mapping:

```rust
pub enum CostMapping {
  Raw,
  Scalar { value: f64 },
  // leaving room for extension if we need to do any fancier maths, maybe not needed
  Poly2 { x0: f64, x1: f64 }, 
  Exp { base: f64, exp_coefficient: f64 },
  Combined(Vec<CostMapping>),
  ...
}

pub struct CostMappingConfiguration {
  distance: Option<CostMapping>,
  time: Option<CostMapping>,
  energy: Option<CostMapping>,
  // ... future units here
}

impl CostMappingConfiguration {
  pub fn distance_cost(&self) -> Result<Option<Cost>, Error> {} 
  // ... etc
}
```

and users could specify that in configuration, assumed to match units in the traversal model:

```toml
[traversal.cost]
distance_cost = { type = "scalar", value = 0.0123 }  # some mileage-based cost factor
time_cost = { type = "scalar", value = 0.0456 }  # some value-of-time cost factor
energy_cost = { type = "scalar", value = 0.00789 } # some price per KwH, possibly based on charging
aggregation = "sum"
```

the user could provide a cost for any unit type, and then the traversal model scoops up from this whatever cost mapping it needs.

the only potential problem here is that the mapping is 1:1 with the unit type. that _may_ be too simple for users who may want to come up with a mix of costs. or it may be fine, they may be able to pre-compute how those factors reduce to a single factor, or they may be able to make use of the Combined approach for that too.
